# Generated by Django 4.2.17 on 2025-01-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoPerson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
            ],
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
