[project]
name = "platform"
version = "2.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "asgiref==3.8.1",
    "django==5.2.11",
    "djangorestframework==3.16.1",
    "gunicorn==23.0.0",
    "nanoid==2.0.0",
    "packaging==24.0",
    "psycopg==3.2.10",
    "python-dotenv==1.0.1",
    "sqlparse==0.5.4",
    "typing-extensions==4.11.0",
    "whitenoise==6.6.0",
]

[dependency-groups]
dev = [
    "djangorestframework-stubs>=3.16.7",
    "django-stubs==5.2.9",
    "ruff>=0.5.7",
    "pytest==8.3.4",
    "pytest-django==4.11.1",
    "scipy-stubs>=1.16.3.1",
    "ty>=0.0.12",
]

[tool.ruff]
target-version = "py311"
line-length = 120
indent-width = 2
exclude = [
    ".git",
    "./env",
    ".venv",
    "./**/migrations/"
]

[tool.ruff.format]
indent-style = "tab"
line-ending = "lf"

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]

[tool.ruff.lint]
select = ["I", "N"]
extend-select = ["E501", "I"]
